# Generated by Django 2.2 on 2020-04-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogx', '0005_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
