# Generated by Django 2.2 on 2020-05-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogx', '0009_auto_20200520_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
