# Generated by Django 2.2 on 2020-05-22 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogx', '0012_auto_20200521_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug2',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
